#!/bin/bash
docker run --rm --net=host -it \
       -v ~/gulp-tool:/gulp-tool \
       -v ~/gulp-env:/gulp-env \
	   -v /var/run/docker.sock:/var/run/docker.sock \
	   -v $(pwd):/work \
	   david6miji/gulp-tool:latest \
	   $*
